# fly.toml app configuration file generated for blog-long-moon-4955 on 2025-01-26T22:39:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-long-moon-4955'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
